export const fatSecretRecipesDE = [
  {id: 1, fsId: '8866808', name: 'Asia Pfanne', hint: 'Achte auf die Zutaten'},
  {id: 2, fsId: '8307492', name: 'Pfannkuchen', hint: 'Achte auf die Zutaten'},
  {id: 3, fsId: '5373738', name: 'Nudel Spinat Auflauf', hint: 'Achte auf die Zutaten'},
  {id: 4, fsId: '8953356', name: 'Zucchini', hint: 'Große Portion'},
  {id: 5, fsId: '11736480', name: 'Wraps', hint: 'Eine Portion entspricht zwei kleinen Wraps'},
  {id: 6, fsId: '9216766', name: 'Omelette', hint: 'Das Omelette auf dem Bild wurde zusammengeklappt'},
  {id: 7, fsId: '8447633', name: 'Kürbissuppe', hint: 'Achte auf die Zutaten'},
  {id: 8, fsId: '8289890', name: 'Kürbissuppe + Ingwer', hint: 'Achte auf die Zutaten'},
  {id: 9, fsId: '8285578', name: 'Kartoffelpuffer', hint: 'Eine Portion entspricht ca. 4-5 Puffer'},
  {id: 10, fsId: '13291554', name: 'Protein Riegel', hint: 'Eine Portion entspricht einem Power Riegel'},
  {id: 11, fsId: '12119207', name: 'Waffeln', hint: 'Wenig Kohlenhydrate. Eine Port entspricht einer Waffel'},
  {
    id: 12,
    fsId: '9661813',
    name: 'Low Carb Waffeln - Belgisch',
    hint: 'Die 4 Waffel-Stücke auf dem Foto entsprechen einer Portion. Aber Achtung es sind Low Carb Waffeln',
  },
  {id: 13, fsId: '8215434', name: 'Eiweißbrot', hint: 'Eine Portion entspricht einer Scheibe'},
  {id: 14, fsId: '7536700', name: 'Brötchen', hint: 'Es geht um ein Brötchen. Achte auf die Zutaten'},
  {id: 15, fsId: '13673494', name: 'Salat', hint: null},
  {id: 16, fsId: '12365528', name: 'Schoko Creme Kuchen', hint: 'Schoko Creme Kuchen Stück'},
  {id: 17, fsId: '12260350', name: 'Onigiri', hint: 'Eine Portion entspricht einem Onigiri.'},
  {id: 18, fsId: '9790373', name: 'Apfelkuchen', hint: 'Kleine Portion / kleiner Teller'},
  {id: 19, fsId: '9210174', name: 'Apfel-Quark-Kuchen', hint: 'Ein Stück Kuchen'},
  {id: 20, fsId: '8583758', name: 'Milchreis', hint: 'Nimm dir die Zutaten zur Hilfe'},
  {id: 21, fsId: '7913319', name: 'Melonensalat mit Putenfilet', hint: 'Nimm dir die Zutaten zur Hilfe'},
  {id: 22, fsId: '7529192', name: 'Erdbeerquark', hint: 'Nimm dir die Zutaten zur Hilfe'},
  {id: 23, fsId: '6906467', name: 'Spaghetti', hint: 'Eine Portion hat 125g Nudeln'},
  {
    id: 24,
    fsId: '5803093',
    name: 'Tiramisu',
    hint: 'Auf dem Foto sind 10 Portionen. Gefragt ist nach einer Portion',
  },
  {id: 25, fsId: '5444848', name: 'Pilzsuppe', hint: null},
  {
    id: 26,
    fsId: '5319674',
    name: 'Kartoffeln',
    hint: 'Eine Portion enthält 250g Kartoffeln. Das sind zwei große Kartoffeln',
  },
  {
    id: 27,
    fsId: '5314050',
    name: 'Hühnchenpfanne',
    hint: 'Wirf einen Blick in die Zutaten und die Anzahl der Portionen',
  },
  {
    id: 28,
    fsId: '5285810',
    name: 'Reissalat',
    hint: 'Wirf einen Blick in die Zutaten und die Anzahl der Portionen',
  },
  {
    id: 29,
    fsId: '5631993',
    name: 'Hähnchen-Gemüse-Pfanne',
    hint: 'Wirf einen Blick in die Zutaten und die Anzahl der Portionen',
  },
  {
    id: 30,
    fsId: '5907451',
    name: 'Fischfrikadellen',
    hint: 'Wirf einen Blick in die Zutaten und die Anzahl der Portionen',
  },
  {
    id: 31,
    fsId: '5882821',
    name: 'Tomaten Grill',
    hint: 'Eine Portion entspricht 2 mittelgroßen Tomaten',
  },
  {
    id: 32,
    fsId: '5870050',
    name: 'Kartoffel Salat',
    hint: 'Kleine Portion. Die Zutaten reichen für deutlich mehr',
  },
  {
    id: 33,
    fsId: '5690700',
    name: 'Nudeln',
    hint: 'Kleine Portion (75g Nudeln)',
  },
  {
    id: 34,
    fsId: '6053061',
    name: 'Bohnen Topf',
    hint: null,
  },
  {
    id: 35,
    fsId: '6109558',
    name: 'Möhren Zucchini Puffer',
    hint: null,
  },
  {
    id: 36,
    fsId: '6941042',
    name: 'Torte',
    hint: null,
  },
  {
    id: 37,
    fsId: '6924120',
    name: 'Tomaten Suppe',
    hint: null,
  },
  {
    id: 38,
    fsId: '6691128',
    name: 'Brotkuchen',
    hint: 'Kleine Portion',
  },
];

export const fatSecretRecipesEN = [
  {id: 1, fsId: '8956150', name: null, hint: 'Have a look at the recipe'},
  {id: 2, fsId: '22594555', name: null, hint: 'Have a look at the recipe'},
  {id: 3, fsId: '7160796', name: null, hint: 'Have a look at the recipe'},
  {id: 4, fsId: '5143006', name: null, hint: 'Have a look at the recipe'},
  {id: 5, fsId: '7042229', name: null, hint: 'Have a look at the recipe'},
  {id: 6, fsId: '67516', name: null, hint: 'Have a look at the recipe'},
  {id: 7, fsId: '8016123', name: null, hint: 'Have a look at the recipe'},
  {id: 8, fsId: '1586500', name: null, hint: 'Have a look at the recipe'},
  {id: 9, fsId: '4244734', name: null, hint: 'Have a look at the recipe'},
  {id: 10, fsId: '8937887', name: null, hint: 'Have a look at the recipe'},
  {id: 11, fsId: '4492179', name: null, hint: 'Have a look at the recipe'},
  {id: 12, fsId: '614', name: null, hint: 'Have a look at the recipe'},
  {id: 13, fsId: '778742', name: null, hint: 'Have a look at the recipe'},
  {id: 14, fsId: '1254025', name: null, hint: 'Have a look at the recipe'},
  {id: 15, fsId: '268436', name: null, hint: 'Have a look at the recipe'},
  {id: 16, fsId: '5760302', name: null, hint: 'Have a look at the recipe'},
  {id: 17, fsId: '11046680', name: null, hint: 'Have a look at the recipe'},
  {id: 18, fsId: '5973094', name: null, hint: 'Have a look at the recipe'},
  {id: 19, fsId: '8281604', name: null, hint: 'Have a look at the recipe'},
  {id: 20, fsId: '4779131', name: null, hint: 'Have a look at the recipe'},
  {id: 21, fsId: '197356', name: null, hint: 'Have a look at the recipe'},
  {id: 22, fsId: '7046402', name: null, hint: 'Have a look at the recipe'},
];
