require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'meala' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

    permissions_path = '../node_modules/react-native-permissions/ios'
    pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
     pod 'AppAuth'

  target 'mealaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  use_flipper!({ 'Flipper' => '0.79.1' })
  post_install do |installer|
    #flipper_post_install(installer)
  end
end
